# Generated by Django 5.1.4 on 2025-02-16 20:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orientacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tb_orientacao',
            },
        ),
        migrations.CreateModel(
            name='Pavimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tb_pavimento',
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Relatório')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'db_table': 'tb_relatorio',
            },
        ),
        migrations.CreateModel(
            name='SensorFisico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=150, null=True)),
                ('tensao_min', models.FloatField()),
                ('tensao_max', models.FloatField()),
            ],
            options={
                'db_table': 'tb_sensorfisico',
            },
        ),
        migrations.CreateModel(
            name='TipoSensor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50)),
                ('limite_inferior_permitido', models.FloatField()),
                ('limite_superior_permitido', models.FloatField()),
                ('unidade', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tb_tiposensor',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('id_orientacao', models.ForeignKey(db_column='id_orientacao', null=True, on_delete=django.db.models.deletion.RESTRICT, to='clima.orientacao')),
                ('id_pavimento', models.ForeignKey(db_column='id_pavimento', null=True, on_delete=django.db.models.deletion.RESTRICT, to='clima.pavimento')),
            ],
            options={
                'db_table': 'tb_sala',
            },
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='leituras', to='clima.sala')),
            ],
            options={
                'db_table': 'tb_leitura',
            },
        ),
        migrations.CreateModel(
            name='SensorLogico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50)),
                ('sensor_fisico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clima.sensorfisico')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clima.tiposensor')),
            ],
            options={
                'db_table': 'tb_sensorlogico',
            },
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
                ('sensor_logico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clima.sensorlogico')),
            ],
            options={
                'db_table': 'tb_parametro',
            },
        ),
        migrations.CreateModel(
            name='LeituraSensor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('leitura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras_sensores', to='clima.leitura')),
                ('sensor_logico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='leituras_sensores', to='clima.sensorlogico')),
            ],
            options={
                'db_table': 'tb_leitura_sensor',
            },
        ),
    ]
