# Generated by Django 5.1.4 on 2025-02-03 13:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Dashboard')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
            },
        ),
        migrations.CreateModel(
            name='Orientacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Orientação')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Orientação',
                'verbose_name_plural': 'Orientações',
            },
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Parâmetro')),
                ('unidade', models.CharField(max_length=20, verbose_name='Unidade de Medida')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Parâmetro',
                'verbose_name_plural': 'Parâmetros',
            },
        ),
        migrations.CreateModel(
            name='Pavimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Pavimento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('andar', models.PositiveIntegerField(verbose_name='Número do Andar')),
                ('localizacao', models.CharField(max_length=100, verbose_name='Localização')),
            ],
            options={
                'verbose_name': 'Pavimento',
                'verbose_name_plural': 'Pavimentos',
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Relatório')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatorios',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Sala')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('capacidade', models.PositiveIntegerField(verbose_name='Capacidade da Sala')),
                ('localizacao', models.CharField(max_length=100, verbose_name='Localização')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.CreateModel(
            name='TipoSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Sensor')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('limite_inferior_permitido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Limite Inferior Permitido')),
            ],
            options={
                'verbose_name': 'Tipo de Sensor',
                'verbose_name_plural': 'Tipos de Sensores',
            },
        ),
        migrations.CreateModel(
            name='SensorFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=100, verbose_name='Localização')),
                ('data_instalacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Instalação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Sensor Ativo')),
                ('pavimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clima.pavimento', verbose_name='Pavimento')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clima.sala', verbose_name='Sala')),
                ('tipo_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clima.tiposensor', verbose_name='Tipo de Sensor')),
            ],
            options={
                'verbose_name': 'Sensor Físico',
                'verbose_name_plural': 'Sensores Físicos',
            },
        ),
        migrations.CreateModel(
            name='SensorLogico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Sensor Ativo')),
                ('data_instalacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Instalação')),
                ('sensor_fisico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logico', to='clima.sensorfisico', verbose_name='Sensor Físico')),
                ('tipo_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clima.tiposensor', verbose_name='Tipo de Sensor')),
            ],
            options={
                'verbose_name': 'Sensor Lógico',
                'verbose_name_plural': 'Sensores Lógicos',
            },
        ),
        migrations.CreateModel(
            name='LeituraTemperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura')),
                ('data_leitura', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Leitura')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clima.tiposensor')),
            ],
            options={
                'verbose_name': 'Leitura de Temperatura',
                'verbose_name_plural': 'Leituras de Temperatura',
            },
        ),
    ]
