# Generated by Django 5.1.5 on 2025-02-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Dashboard')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Sala')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('capacidade', models.PositiveIntegerField(verbose_name='Capacidade da Sala')),
                ('localizacao', models.CharField(max_length=100, verbose_name='Localização')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.CreateModel(
            name='TipoSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Sensor')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('limite_inferior_permitido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Limite Inferior Permitido')),
            ],
            options={
                'verbose_name': 'Tipo de Sensor',
                'verbose_name_plural': 'Tipos de Sensores',
            },
        ),
    ]
