# Generated by Django 5.1.4 on 2025-02-16 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorlogico',
            name='sensor_fisico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sensor_logicos', to='clima.sensorfisico'),
        ),
        migrations.AlterField(
            model_name='sensorlogico',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sensor_logicos', to='clima.tiposensor'),
        ),
    ]
