# Generated by Django 5.1.4 on 2025-02-10 13:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clima.sala')),
            ],
        ),
        migrations.CreateModel(
            name='LeituraSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_leitura', models.IntegerField(verbose_name='ID da Leitura')),
                ('valor', models.FloatField(verbose_name='Valor da Leitura')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data da Leitura')),
                ('sensor_logico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clima.sensorlogico', verbose_name='Sensor Lógico')),
            ],
            options={
                'verbose_name': 'Leitura de Sensor',
                'verbose_name_plural': 'Leituras de Sensores',
            },
        ),
        migrations.DeleteModel(
            name='LeituraTemperatura',
        ),
    ]
