# Generated by Django 5.1.5 on 2025-02-02 06:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0002_parametro'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeituraTemperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura')),
                ('data_leitura', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Leitura')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clima.tiposensor')),
            ],
            options={
                'verbose_name': 'Leitura de Temperatura',
                'verbose_name_plural': 'Leituras de Temperatura',
            },
        ),
    ]
